Numpy Quickstart

`https://laboputer.github.io/machine-learning/2020/04/25/numpy-quickstart/`
`https://numpy.org/devdocs/user/quickstart.html`

In [2]:
import numpy as np
import numpy.random as npr


In [13]:
a = np.arange(15).reshape(3, 5)
# Error!
#b = np.arange(15).reshape(4, 5)
print(a)


[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]


In [10]:
print(a.shape)
print(a.ndim)
print(a.dtype)
print(a.itemsize)
print(a.size)
np.ndarray(type(a))


(3, 5)
2
int32


In [14]:
b = np.linspace(0, np.pi,3)
print(b)

[0.         1.57079633 3.14159265]


In [16]:
a = np.array([2, 3, 4])
print(a, a.dtype)
b = np.array([1.2, 3.5, 5.1])
print(b, b.dtype)

[2 3 4] int32
[1.2 3.5 5.1] float64


In [20]:
b = np.array([[1.5, 2.3, np.NaN], [4, 5, 6]])
print(b)
print(b.dtype)

[[1.5 2.3 nan]
 [4.  5.  6. ]]
float64


In [23]:
c = np.array([[1, 2], [3, 4]], dtype=complex)
print(c)

[[1.+0.j 2.+0.j]
 [3.+0.j 4.+0.j]]


In [30]:
print(repr(np.zeros((3, 4))))

print(repr(np.ones((2, 3, 4), dtype=np.int16)))
print()
print(np.empty((2, 3)))


array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])
array([[[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]]], dtype=int16)

[[1.39069238e-309 1.39069238e-309 1.39069238e-309]
 [1.39069238e-309 1.39069238e-309 1.39069238e-309]]


In [35]:
print(np.arange(10, 30, 5))
print(np.arange(0, 2, 0.3))

x = np.linspace(0, 99, 100)
print(x)



[10 15 20 25]
[0.  0.3 0.6 0.9 1.2 1.5 1.8]
[ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15. 16. 17.
 18. 19. 20. 21. 22. 23. 24. 25. 26. 27. 28. 29. 30. 31. 32. 33. 34. 35.
 36. 37. 38. 39. 40. 41. 42. 43. 44. 45. 46. 47. 48. 49. 50. 51. 52. 53.
 54. 55. 56. 57. 58. 59. 60. 61. 62. 63. 64. 65. 66. 67. 68. 69. 70. 71.
 72. 73. 74. 75. 76. 77. 78. 79. 80. 81. 82. 83. 84. 85. 86. 87. 88. 89.
 90. 91. 92. 93. 94. 95. 96. 97. 98. 99.]
